# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e003ecabe60c7e4cc08a44f77173879f8b78e85b14d607a91797e72710ca603
# To regenerate: alef generate
# To verify freshness: alef verify
"""Exception hierarchy (re-exported from the native module)."""

from ._html_to_markdown import (
    ConfigError,
    ConversionError,
    InvalidInputError,
    IoError,
    OtherError,
    PanicError,
    ParseError,
    SanitizationError,
)

__all__ = [
    "ConfigError",
    "ConversionError",
    "InvalidInputError",
    "IoError",
    "OtherError",
    "PanicError",
    "ParseError",
    "SanitizationError",
]

# Re-point each exception's __module__ at the public package so tracebacks show the
# public name (e.g. "DownloadError"), not the native module name (GitHub issue #147).
_public_module = __name__.rsplit(".", 1)[0]
for _name in __all__:
    globals()[_name].__module__ = _public_module
del _name, _public_module
